"""Make community_id nullable in posts table.

Revision ID: b0ca7e4c35e7
Revises: 7b1829b57519
Create Date: 2025-02-27 10:56:13.788717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ca7e4c35e7'
down_revision = '7b1829b57519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('community_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('community_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
