"""Create communities table

Revision ID: 156e6e2a6446
Revises: b0ca7e4c35e7
Create Date: 2025-02-27 13:37:39.395705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156e6e2a6446'
down_revision = 'b0ca7e4c35e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communities')
    # ### end Alembic commands ###
