"""create comment_likes table

Revision ID: 5157fa287807
Revises: e79253ed8b23
Create Date: 2025-02-28 17:51:24.323424

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '5157fa287807'
down_revision = 'e79253ed8b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'comment_likes',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('comment_id', sa.Integer, sa.ForeignKey('comments.id', ondelete='CASCADE'), nullable=False),
        sa.Column('created_at', sa.DateTime, default=sa.func.current_timestamp(), nullable=False),
        sa.Column('updated_at', sa.DateTime, default=sa.func.current_timestamp(), onupdate=sa.func.current_timestamp(), nullable=False),
    )

    if environment == "production":
        op.execute(f"ALTER TABLE comment_likes SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_likes')
    # ### end Alembic commands ###
